### ISSUE TITLE
Add `read` for new queues

### ISSUE THREAD

**Issue by dpipemazo** [elementary-robotics/atom#427]
Once #404 is merged, there's one API that would be great to have: the ability to read from the queue without consuming (introspection). This is a huge advantage to the redis sorted set over the Python Multiprocessing Queue.

It should be fairly straightforward to implement using a `ZRANGE` or similar command and an API similar to `get_n`. 

What do you think we should call it? `read` is OK but `inspect` might be better? Open to ideas on this.

**Comment by slaigai** [comment]
I agree, this would have been useful in one of my other PRs. 

I think we could call it "peek". Like "look but don't touch". Personally, I agree that "read" is OK because it makes me think of file readers that consume lines as they parse files. I associate "inspect" with inspection of the queue's properties rather than its items but I might be in the minority with this viewpoint (maybe).

**Comment by dpipemazo** [comment]
`peek` sounds great to me!
